export const GET_ALL_FLIGHT_DETAILS_REQUEST = "GET_ALL_FLIGHT_DETAILS_REQUEST"

export const GET_ALL_FLIGHT_DETAILS_SUCCESS = "GET_ALL_FLIGHT_DETAILS_SUCCESS"

export const GET_ALL_FLIGHT_DETAILS_FAILS = "GET_ALL_FLIGHT_DETAILS_FAILS"

export const FILE_UPLOAD_REQUEST = "FILE_UPLOAD_REQUEST"

export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"

export const FILE_UPLOAD_FAILS = "FILE_UPLOAD_FAILS"

export const AIRLINES_UPLOAD_REQUEST = "AIRLINES_UPLOAD_REQUEST"

export const AIRLINES_UPLOAD_SUCCESS = "AIRLINES_UPLOAD_SUCCESS"

export const AIRLINES_UPLOAD_FAILS = "AIRLINES_UPLOAD_FAILS"

export const GET_ALL_AIRPORT_DETAILS_REQUEST = "GET_ALL_AIRPORT_DETAILS_REQUEST"

export const GET_ALL_AIRPORT_DETAILS_SUCCESS = "GET_ALL_AIRPORT_DETAILS_SUCCESS"

export const GET_ALL_AIRPORT_DETAILS_FAILS = "GET_ALL_AIRPORT_DETAILS_FAILS"

export const ADMIN_PRE_FLIGHT_BOOKING_REQUEST = "ADMIN_PRE_FLIGHT_BOOKING_REQUEST"

export const ADMIN_PRE_FLIGHT_BOOKING_SUCCESS = "ADMIN_PRE_FLIGHT_BOOKING_SUCCESS"

export const ADMIN_PRE_FLIGHT_BOOKING_FAILS = "ADMIN_PRE_FLIGHT_BOOKING_FAILS"