export const GET_ALL_AIRPORT_DETAILS_REQUEST = "GET_ALL_AIRPORT_DETAILS_REQUEST"

export const GET_ALL_AIRPORT_DETAILS_SUCCESS = "GET_ALL_AIRPORT_DETAILS_SUCCESS"

export const GET_ALL_AIRPORT_DETAILS_FAILS = "GET_ALL_AIRPORT_DETAILS_FAILS"

export const GET_FLIGHT_DETAILS_REQUEST = "GET_FLIGHT_DETAILS_REQUEST"

export const GET_FLIGHT_DETAILS_SUCCESS = "GET_FLIGHT_DETAILS_SUCCESS"

export const GET_FLIGHT_DETAILS_FAILS = "GET_FLIGHT_DETAILS_FAILS"

export const GET_WEEKLY_FLIGHT_DETAILS_REQUEST = "GET_WEEKLY_FLIGHT_DETAILS_REQUEST"

export const GET_WEEKLY_FLIGHT_DETAILS_SUCCESS = "GET_WEEKLY_FLIGHT_DETAILS_SUCCESS"

export const GET_WEEKLY_FLIGHT_DETAILS_FAILS = "GET_WEEKLY_FLIGHT_DETAILS_FAILS"

export const PRE_FLIGHT_BOOKING_REQUEST = "PRE_FLIGHT_BOOKING_REQUEST"

export const PRE_FLIGHT_BOOKING_SUCCESS = "PRE_FLIGHT_BOOKING_SUCCESS"

export const PRE_FLIGHT_BOOKING_FAILS = "PRE_FLIGHT_BOOKING_FAILS"